Plugins.PostgreSQL.Sessions.app.Uri=tcp://host.docker.internal:5432
Plugins.PostgreSQL.Sessions.app.User=zbx_monitor
Plugins.PostgreSQL.Sessions.app.Password=zbx_monitor
Plugins.PostgreSQL.Sessions.app.Database=order_events
Plugins.PostgreSQL.CustomQueriesPath=/etc/zabbix/custom-queries
